### ISSUE TITLE
Rendering in Word format

### ISSUE THREAD

**Issue by Valentin-Bio** [kelly-sovacool/asm-msystems#5]
Hello Developer! I have written a journal using your template. I have rendered it in pdf format and everything looks fine including cites and the References section. My problem is want to share my document with one of the co-authors so he can suggest changes to the document. This co-author can only give me feedback if the document is in Word format. After using the below yml code I got the document rendered but some pdf images lost part of their contents, but the most important thing is the references section doesn't exist in the rendered Word document. so How can I make the references section appear in the Word-rendered document? 

```
---
format:
  asm-docx:
    keep-tex: true
    classoption:
      - lineno
    docx-engine: docxlatex
    indent: true
runningtitle: Running Title
runningauthor: Valentín Berríos-Farías
papertype: Research Article
(...)
```
